---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test_build
  pull: always
  image: quay.io/ukhomeofficedigital/cop-node:13
  commands:
  - npm install
  - npm audit --audit-level=moderate
  - npm test
  - npm run build:dev
  when:
    event:
    - pull_request

- name: pr_sonarqube_scan
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/sonar-scanner-node:latest
  when:
    event:
    - pull_request

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server

...
